/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicagui;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author danie
 */
public class frmElectrodomesticos extends javax.swing.JFrame {

    /**
     * Creates new form frmElectrodomesticos
     */
    public frmElectrodomesticos() {
        initComponents();
        this.pnlLavadora.setVisible(false);
        this.pnlElectrodomestico.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupArticulo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlArticulo = new javax.swing.JPanel();
        rdbElectrodomestico = new javax.swing.JRadioButton();
        rdbLavadora = new javax.swing.JRadioButton();
        pnlElectrodomestico = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbColor = new javax.swing.JComboBox<>();
        txtConsumo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        pnlLavadora = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtCarga = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtISV = new javax.swing.JTextField();
        txtSubtotal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Venta de Electrodomesticos y Lavadoras");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 20, -1, -1));

        pnlArticulo.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Articulo"));

        GroupArticulo.add(rdbElectrodomestico);
        rdbElectrodomestico.setText("Electrodomestico");
        rdbElectrodomestico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbElectrodomesticoActionPerformed(evt);
            }
        });

        GroupArticulo.add(rdbLavadora);
        rdbLavadora.setText("Lavadora");
        rdbLavadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbLavadoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlArticuloLayout = new javax.swing.GroupLayout(pnlArticulo);
        pnlArticulo.setLayout(pnlArticuloLayout);
        pnlArticuloLayout.setHorizontalGroup(
            pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArticuloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbElectrodomestico)
                    .addComponent(rdbLavadora))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlArticuloLayout.setVerticalGroup(
            pnlArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArticuloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdbElectrodomestico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbLavadora)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(pnlArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 232, -1));

        pnlElectrodomestico.setBorder(javax.swing.BorderFactory.createTitledBorder("Electrodomestico"));

        jLabel2.setText("Color:");

        jLabel3.setText("Consumo: ");

        cmbColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blanco", "Negro", "Rojo ", "Azul  ", "Gris", " " }));
        cmbColor.setSelectedIndex(-1);

        jLabel4.setText("Peso: ");

        javax.swing.GroupLayout pnlElectrodomesticoLayout = new javax.swing.GroupLayout(pnlElectrodomestico);
        pnlElectrodomestico.setLayout(pnlElectrodomesticoLayout);
        pnlElectrodomesticoLayout.setHorizontalGroup(
            pnlElectrodomesticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlElectrodomesticoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlElectrodomesticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlElectrodomesticoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32)
                        .addComponent(cmbColor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlElectrodomesticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlElectrodomesticoLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlElectrodomesticoLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        pnlElectrodomesticoLayout.setVerticalGroup(
            pnlElectrodomesticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlElectrodomesticoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlElectrodomesticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlElectrodomesticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlElectrodomesticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(pnlElectrodomestico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 163, 230, -1));

        pnlLavadora.setBorder(javax.swing.BorderFactory.createTitledBorder("Lavadora"));

        jLabel5.setText("Carga:");

        javax.swing.GroupLayout pnlLavadoraLayout = new javax.swing.GroupLayout(pnlLavadora);
        pnlLavadora.setLayout(pnlLavadoraLayout);
        pnlLavadoraLayout.setHorizontalGroup(
            pnlLavadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLavadoraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        pnlLavadoraLayout.setVerticalGroup(
            pnlLavadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLavadoraLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlLavadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(pnlLavadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 240, -1));

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        jLabel6.setText("Subtotal: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));

        jLabel8.setText("Total:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        txtTotal.setEditable(false);
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 70, -1));

        txtISV.setEditable(false);
        jPanel1.add(txtISV, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 70, -1));

        txtSubtotal.setEditable(false);
        txtSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubtotalActionPerformed(evt);
            }
        });
        jPanel1.add(txtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 70, -1));

        jLabel9.setText("ISV:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtotalActionPerformed

    private void rdbLavadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbLavadoraActionPerformed

        if (this.rdbLavadora.isSelected())
        {
            this.pnlLavadora.setVisible(true);
            this.pnlElectrodomestico.setVisible(false);
            this.cmbColor.setSelectedIndex(-1);
            this.txtCarga.setText("");
            this.txtConsumo.setText("");
            this.txtPeso.setText("");
            this.txtSubtotal.setText("");
        }

    }//GEN-LAST:event_rdbLavadoraActionPerformed

    private void rdbElectrodomesticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbElectrodomesticoActionPerformed
        if (this.rdbElectrodomestico.isSelected())
        {
            this.pnlLavadora.setVisible(false);
            this.pnlElectrodomestico.setVisible(true);
            this.txtCarga.setText("");
            this.txtSubtotal.setText("");
        }
    }//GEN-LAST:event_rdbElectrodomesticoActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        
        Conexion con = new Conexion();
        
        if (this.rdbElectrodomestico.isSelected())
        {
            Electrodomesticos electrodomesticos = new Electrodomesticos();
            
            if(this.cmbColor.getSelectedIndex()==-1)
            {
               electrodomesticos.setColor(""); 
               this.cmbColor.setSelectedItem(electrodomesticos.comprobarColor());
            }
            else
            {
                electrodomesticos.setColor(this.cmbColor.getSelectedItem().toString()); 
                this.cmbColor.setSelectedItem(electrodomesticos.comprobarColor());
            }
            
            if (this.txtConsumo.getText().isEmpty())
            {
                electrodomesticos.setConsumo('U');
                this.txtConsumo.setText(electrodomesticos.comprobarConsumoEnergetico().toString());
            }
            else
            {
                electrodomesticos.setConsumo(txtConsumo.getText().toUpperCase().charAt(0));
                this.txtConsumo.setText(electrodomesticos.comprobarConsumoEnergetico().toString());
            }

            if (this.txtPeso.getText().isEmpty())
            {
                electrodomesticos.setPeso(0);
                this.txtPeso.setText("5");
            }
                
            else
                electrodomesticos.setPeso(Integer.parseInt(this.txtPeso.getText()));

            this.txtSubtotal.setText(String.valueOf(electrodomesticos.precioFinal())); 
            
            con.Ingresar(this.rdbElectrodomestico.getText(), this.cmbColor.getSelectedItem().toString(),this.txtConsumo.getText().charAt(0), Integer.parseInt(this.txtPeso.getText()), null);
        }
        
        if (this.rdbLavadora.isSelected())
        {
            Lavadora lavadora = new Lavadora();
            
            if(this.txtCarga.getText().isEmpty())
            {
                this.txtCarga.setText(String.valueOf(lavadora.carga_default));
                lavadora.setCarga(lavadora.carga_default);
            }
            else
            {
                lavadora.setCarga(Integer.parseInt(this.txtCarga.getText()));
            }
            
            this.txtSubtotal.setText(String.valueOf(lavadora.precioFinal()));
            
            con.Ingresar(this.rdbLavadora.getText(), null, null, 0, Integer.parseInt(this.txtCarga.getText()));
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
        } catch (ClassNotFoundException ex) {
            //Logger.getLogger(frmElectrodomesticos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            //Logger.getLogger(frmElectrodomesticos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            //Logger.getLogger(frmElectrodomesticos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            //Logger.getLogger(frmElectrodomesticos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmElectrodomesticos().setVisible(true);
                
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GroupArticulo;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JComboBox<String> cmbColor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlArticulo;
    private javax.swing.JPanel pnlElectrodomestico;
    private javax.swing.JPanel pnlLavadora;
    private javax.swing.JRadioButton rdbElectrodomestico;
    private javax.swing.JRadioButton rdbLavadora;
    private javax.swing.JTextField txtCarga;
    private javax.swing.JTextField txtConsumo;
    private javax.swing.JTextField txtISV;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
