/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectocasaempeños;



import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luisf
 */
public class Inventario extends javax.swing.JFrame {

    /**
     * Creates new form Inventario
     */
    public Inventario() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.txtNombreProducto.setTransferHandler(null);
        this.txtPrecioVenta.setTransferHandler(null);
        this.txtCantidad.setTransferHandler(null);
        con.llenarCmbEstadoObjetos(cmbEstado);
        con.llenarTablaInventario(tblInventario);
        this.tblInventario.getColumn(tblInventario.getColumnName(0)).setWidth(0);
        //this.tblInventario.getColumn(0).setWidth(0);
    }

    Conexion con = new Conexion();
    java.util.Date d = new java.util.Date();  
    SimpleDateFormat plantilla = new SimpleDateFormat("yyyy/MM/dd H:mm:ss");
    //java.sql.Date fechaActual = new java.sql.Date(d.getTime());
    String fechaActual = plantilla.format(d.getTime());
    
    Integer codigo;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblNombreProducto = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        txtNombreProducto = new javax.swing.JTextField();
        txtPrecioVenta = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        lblFiltro = new javax.swing.JLabel();
        cmbFiltro = new javax.swing.JComboBox<>();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventario = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultar/modificar objetos");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblTitulo.setText("Consultar/Modificar objetos");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblCantidad.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblCantidad.setText("Cantidad: ");
        jPanel1.add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 125, -1, -1));

        lblEstado.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblEstado.setText("Estado: ");
        jPanel1.add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 85, -1, -1));

        lblPrecio.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblPrecio.setText("Precio venta: ");
        jPanel1.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 125, -1, -1));

        lblNombreProducto.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblNombreProducto.setText("Nombre producto: ");
        jPanel1.add(lblNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 85, -1, -1));

        cmbEstado.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cmbEstado.setEnabled(false);
        jPanel1.add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 170, -1));

        txtNombreProducto.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtNombreProducto.setEnabled(false);
        jPanel1.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 180, -1));

        txtPrecioVenta.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtPrecioVenta.setEnabled(false);
        jPanel1.add(txtPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 100, -1));

        txtCantidad.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCantidad.setEnabled(false);
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 100, -1));

        lblFiltro.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblFiltro.setText("Filtro: ");
        jPanel1.add(lblFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 175, -1, -1));

        cmbFiltro.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cmbFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estado", "Nombre", "Precio" }));
        jPanel1.add(cmbFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 120, -1));

        lblBuscar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblBuscar.setText("Buscar: ");
        jPanel1.add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 175, -1, -1));

        txtBuscar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 180, -1));

        btnCancelar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 167, -1, 30));

        btnConsultar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 167, -1, 30));

        btnModificar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setEnabled(false);
        btnModificar.setMinimumSize(new java.awt.Dimension(957, 27));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 167, -1, 30));

        tblInventario.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Estado", "Nombre", "Cantidad disponible", "Precio venta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInventarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblInventario);
        if (tblInventario.getColumnModel().getColumnCount() > 0) {
            tblInventario.getColumnModel().getColumn(0).setResizable(false);
            tblInventario.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblInventario.getColumnModel().getColumn(1).setPreferredWidth(50);
            tblInventario.getColumnModel().getColumn(2).setPreferredWidth(150);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 730, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Clear_Table(){
        DefaultTableModel modelo = (DefaultTableModel) tblInventario.getModel();
        for (int i = 0; i < tblInventario.getRowCount(); i++) {
            modelo.removeRow(i);
            i-=1;
        }
    }
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.txtNombreProducto.setText(null);
        this.txtPrecioVenta.setText(null);
        this.txtCantidad.setText(null);
        this.cmbEstado.setEnabled(false);
        this.txtNombreProducto.setEnabled(false);
        this.txtPrecioVenta.setEnabled(false);
        this.txtCantidad.setEnabled(false);
        this.btnModificar.setEnabled(false);
        this.btnCancelar.setEnabled(false);
        this.tblInventario.clearSelection();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        Clear_Table();
        con.ConsultarTablaInventario(tblInventario, this.cmbFiltro.getSelectedItem().toString(), this.txtBuscar.getText());
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        Clear_Table();
        con.modificar(this.txtNombreProducto.getText(), Integer.parseInt(this.txtCantidad.getText()), Integer.parseInt(this.txtPrecioVenta.getText()), con.obtenerCodigoCmbEstadoObjetos(this.cmbEstado.getSelectedItem().toString())/*this.cmbEstado.getSelectedIndex()+6*/, "luis", this.fechaActual, this.codigo);
        con.llenarTablaInventario(tblInventario);
        this.txtNombreProducto.setText(null);
        this.txtPrecioVenta.setText(null);
        this.txtCantidad.setText(null);
        this.cmbEstado.setEnabled(false);
        this.txtNombreProducto.setEnabled(false);
        this.txtPrecioVenta.setEnabled(false);
        this.txtCantidad.setEnabled(false);
        this.btnModificar.setEnabled(false);
        this.btnCancelar.setEnabled(false);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void tblInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInventarioMouseClicked
        Integer fila = tblInventario.getSelectedRow();
        if(fila>=0){
            this.codigo= Integer.parseInt(tblInventario.getValueAt(fila, 0).toString());
            this.cmbEstado.setSelectedItem(tblInventario.getValueAt(fila, 1).toString());
            this.txtNombreProducto.setText(tblInventario.getValueAt(fila, 2).toString());
            this.txtCantidad.setText(tblInventario.getValueAt(fila, 3).toString());           
            this.txtPrecioVenta.setText(tblInventario.getValueAt(fila, 4).toString());
        }else{
            JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna fila para modificar");
        }
        this.cmbEstado.setEnabled(true);
        this.txtNombreProducto.setEnabled(true);
        this.txtPrecioVenta.setEnabled(true);
        this.txtCantidad.setEnabled(true);
        this.btnModificar.setEnabled(true);
        this.btnCancelar.setEnabled(true);
    }//GEN-LAST:event_tblInventarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbFiltro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFiltro;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblInventario;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecioVenta;
    // End of variables declaration//GEN-END:variables
}
